"""Add scheduled_at column to posts table

Revision ID: 847bc945155b
Revises: 540a8e49e128
Create Date: 2025-07-07 13:11:50.026560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847bc945155b'
down_revision: Union[str, Sequence[str], None] = '540a8e49e128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'scheduled_at')
    # ### end Alembic commands ###
